// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NzaGfp0JglRjugWs_cNtCnTF1oMnLKc',
    appId: '1:185032335553:web:ded12c28ee007900da7440',
    messagingSenderId: '185032335553',
    projectId: 'trade-b4c40',
    authDomain: 'trade-b4c40.firebaseapp.com',
    storageBucket: 'trade-b4c40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXOoLj9Op4x3l6oepuU8KNqfft9a9p4r8',
    appId: '1:185032335553:android:acc5b9e08f864f7cda7440',
    messagingSenderId: '185032335553',
    projectId: 'trade-b4c40',
    storageBucket: 'trade-b4c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkRUCLmrKOtVKROh6Z6CIkD-I_GIe4meg',
    appId: '1:185032335553:ios:18f0e093904327abda7440',
    messagingSenderId: '185032335553',
    projectId: 'trade-b4c40',
    storageBucket: 'trade-b4c40.firebasestorage.app',
    iosBundleId: 'com.bitcoinTracker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkRUCLmrKOtVKROh6Z6CIkD-I_GIe4meg',
    appId: '1:185032335553:ios:18f0e093904327abda7440',
    messagingSenderId: '185032335553',
    projectId: 'trade-b4c40',
    storageBucket: 'trade-b4c40.firebasestorage.app',
    iosBundleId: 'com.bitcoinTracker.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5NzaGfp0JglRjugWs_cNtCnTF1oMnLKc',
    appId: '1:185032335553:web:1473337b947fe989da7440',
    messagingSenderId: '185032335553',
    projectId: 'trade-b4c40',
    authDomain: 'trade-b4c40.firebaseapp.com',
    storageBucket: 'trade-b4c40.firebasestorage.app',
  );

}